### ISSUE TITLE
IL view support

### ISSUE THREAD

**Issue by d-dizhevsky** [icsharpcode/ilspy-vscode#10]
Please consider adding an IL viewer, since this can be done via Roslyn on the fly (in-memory build). 
I'm asking this because I don't see any VS Code extension with such functionality would really work on MacOS at the moment.

I would highly appreciate this feature.

**Comment by jeremymeng** [comment]
I have been thinking about whether the vscode extension can reuse the `CSharpLangauge`, `CSharpMixedLangauge`, and `ILLangauge`, etc.

@siegfriedpammer & @christophwille any thoughts?

**Comment by christophwille** [comment]
Those are intentionally tied to ILSpy (if we considered sharing, they'd be in ics.d)

**Comment by siegfriedpammer** [comment]
As the Language implementations are intended as plugin API in ILSpy, we're not going to move them to ICSharpCode.Decompiler, however we will be moving some features to CSharpDecompiler.

**Comment by jeremymeng** [comment]
What suggestions do you have if we are to add IL support?

**Comment by jeremymeng** [comment]
@siegfriedpammer I added the IL view support. I am not sure whether my usage of  `ReflectionDisassembler` is proper, or there's a better way.  Also the set of the options that are passed might not be great either.

**Comment by jeremymeng** [comment]
![image](https://user-images.githubusercontent.com/7583839/44378400-f28a8400-a4b5-11e8-8ebc-afbeec8626e7.png)
