### ISSUE TITLE
Can't unload a file

### ISSUE THREAD

**Issue by RandallFlagg** [icsharpcode/ilspy-vscode#13]
After opening a file to the view I can't unload it from the view.

If there is an option please refer me to the documentation or explain how to do that. Thanks.

**Comment by hack2root** [comment]
If MSIL assembly was loaded as reflection-only (emit) only assembly it will always be accessible to unload that assembly programmatically, overwize it have to use domain other than current executing domain to be able to unload it from memory completely. Assemblies itself can't me unloaded, only as a domain itself

**Comment by jeremymeng** [comment]
Yes currently the extension does not support unloading/closing an assembly.
