### ISSUE TITLE
"Open code in ILSpy" crashes VS2017 if invoked on some methods.

### ISSUE THREAD

**Issue by tsvx** [icsharpcode/ilspy-vscode#14]
I have a C# ASP.NET Core solution in Visual Studio 2017 and the latest ILSpy extension installed.
When I accidentally try to "Open code in ILSpy" on any my own method, Visual Studio crashes, even if the solution is compiled recently.

Also it crashes on any of the three methods in an invocation chain:
```
WebHost.CreateDefaultBuilder(args)
		.UseStartup<Startup>()
		.Build();
```
(usual ASP.NET Core initialization process).

BTW, ILSpy extension of the latest LINQPad 5 works good on that ASP.NET Core initialization methods.

**Comment by siegfriedpammer** [comment]
This is the repository of the Visual Studio Code extension. The Visual Studio Extension lives at https://github.com/icsharpcode/ILSpy/. Could you please open an issue there? If there is any stacktrace, please include it in the bug report. Thank you!

**Comment by tsvx** [comment]
Oh, sure, sorry!
