### ISSUE TITLE
Overhaul LSP backend interface and make it more generic

### ISSUE THREAD

**Issue by Rpinski** [icsharpcode/ilspy-vscode#152]
When introducing the new LSP backend, the interface protocol (VSCode extension <-> C# backend) has changed to LSP, but semantically the interface stayed the same. The messages for retrieving the items of assembly tree are tied to the tree structure:

```
Assemblies (generated by extension itself)
|
 --> References (parent: generated by extension, children: listAssemblyReferences)
 --> Namespaces (listNamespaces)
     |
      --> Types (listTypes/decompileType)
          |
           --> Members (listMembers/decompileMember)
```

Extending the tree with new nodes involves
* creation of a new set of request/response messages for the new node type in backend (list + decompile)
* the logic in extension to send those messages when a specific node type is extended or opened

Or short: Extension and interface know too much about the tree structure.

To make this more flexible (for example to support things like NuGet packages on same level as assemblies), my idea is to create a generic interface, that is only about "Nodes":

```
-> Extension requests backend for 1st level nodes
<- Backend retrieves generic node objects with metadata
   like type, display name etc. (needed by extension for displaying)

-- User expands a node
-> Extension requests backend for children of the node
   (it just sends the one node object as parameter,
   so backend may place any information it needs to identify
   its kind, type/entity handle etc. in node's metadata)
```

Same applies to decompile interface: Extension just sends a node object with a decompilation request. Backend decides how to decompile it based on the node metadata.

One part of this generic interface is already there, it's used by the search feature (search results are just those generic nodes). But still the extension decides which decompile message (`decompileType` or `decompileMember`) to send when user clicks an entry.

Next steps would be

- [x] 1. Generic `decompileNode` message
- [x] 2. Generic `listNodes` message (used by assembly tree)

**Comment by spouliot** [comment]
💯

**Comment by Rpinski** [comment]
This has been finished with 4bbb7b9
