### ISSUE TITLE
[Request] Go to Decompiled definition

### ISSUE THREAD

**Issue by vchirikov** [icsharpcode/ilspy-vscode#28]
Will be nice if we will have some 'go to decompiled definition' as there is Visual studio has.

**Comment by bitbonk** [comment]
I came here to request exactly the same feature. :) Beeing able to Ctrl+Click on any symbol and then beeing taken to the decompiled (or via SourceLink downloaded) code is an absolute killer feature.

**Comment by stianhoiland** [comment]
This would be great!

**Comment by christophwille** [comment]
This is actually being implemented by the C# extension via OmniSharp. See https://www.strathweb.com/2020/05/decompilation-support-in-omnisharp-and-c-extension-for-vs-code/
