### ISSUE TITLE
Unable to reopen closed window

### ISSUE THREAD

**Issue by fjqingyou** [icsharpcode/ilspy-vscode#29]
### **Environment data**

ILSpy .NET Decompiler 0.7.0

dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

### **Steps to reproduce**

Shift + Commnad + P
![qq20181010-114200](https://user-images.githubusercontent.com/31087168/46712030-97893800-cc81-11e8-8d03-21c076729e1b.png)

selected a .net assembly  dll file

and ,  click it
![qq20181010-114345](https://user-images.githubusercontent.com/31087168/46712106-fea6ec80-cc81-11e8-9d4b-f60183156801.png)

selected a method , auto open double "Untitled" window
![qq20181010-114420](https://user-images.githubusercontent.com/31087168/46712116-141c1680-cc82-11e8-9a83-cf12e2f97de5.png)

close "Untitled 1" and  "Untitled 2" window
![qq20181010-114432](https://user-images.githubusercontent.com/31087168/46712154-3c0b7a00-cc82-11e8-8a61-dc171f772106.png)

selected other method , "Untitled" window Not opened
![qq20181010-114457](https://user-images.githubusercontent.com/31087168/46712169-4cbbf000-cc82-11e8-9a86-0af663b2f606.png)

### **Expected behavior**
selected other method , "Untitled" window reopen

### **Actual behavior**
not opened

**Comment by jeremymeng** [comment]
@fjqingyou Thanks for reporting the issue!  We will have a look.

**Comment by jeremymeng** [comment]
On Windows I am unable to repro this on the latest version 0.7.3.  "Untitled" windows are created as needed.

Closing for now.  Feel free to re-open if the issue still happens on Mac
