### ISSUE TITLE
Is it possible to select the C# language version to decompile into?

### ISSUE THREAD

**Issue by eduarddejong** [icsharpcode/ilspy-vscode#316]
On of the reasons I like decompilation, is for looking in different ways on something, to learn about what the C# compiler generates in different scenarios.

Being able to read pure IL instructions is great an fascinating of course, but having ways to display the code in older or "lowered" C# versions is really useful.
This is one of the things in the desktop application version of ILSpy that I like a lot.
So I believe this feature is probably already part of the core of ILSpy itself as well.

It would be really amazing if it was possible to access that functionality with this VS Code extension as well.

Anyway thanks a lot for making this extension!

**Comment by Rpinski** [comment]
Hi @eduarddejong,
Thank you for your suggestion! The C# language version is part of the decompiler settings in the core, but I'll need to take a thorough look, how to integrate it best into extension's backend.

**Comment by Rpinski** [comment]
I took the chance to clean up extension's internal architecture and implemented selection of different C# versions in #324.

This should come with the next release.

**Comment by Rpinski** [comment]
This feature is now available in 0.18 release.
