### ISSUE TITLE
Improve build scripts

### ISSUE THREAD

**Issue by jeremymeng** [icsharpcode/ilspy-vscode#4]
Some ideas:
* [ ] Exit with error to fail the build when any step fails
* [ ] Add build status badge to README
* [ ] Add a PowerShell script to do the actual build
* [ ] Handle different build environments and version the vsix properly
* [ ] Add a build.sh for *NIX platform

**Comment by christophwille** [comment]
Maybe we should consider going entirely to GH Actions instead of fixing AppVeyor? (we are considering consolidating to one build system in the future for the entire org - currently we mix AppVeyor and Azure DevOps, but ultimately, the goal would be GH Actions)

**Comment by christophwille** [comment]
Andreas has added NUKE and GH Actions, so this issue can be considered completed.
