### ISSUE TITLE
[Feature request] Dump all decompiled, formatted files?

### ISSUE THREAD

**Issue by Valmar33** [icsharpcode/ilspy-vscode#40]
Is there a way to dump all of the decompiled files? Maybe I've just missed the option, if there is one.

If there isn't such an option, can you add one? One that preferably keeps the tree format as seen in the ILSpy tab.

**Comment by christophwille** [comment]
A better fit for such automation tasks might be https://github.com/icsharpcode/ILSpy/tree/master/ICSharpCode.Decompiler.Console (it is x-plat like the VS Code addin here)
