### ISSUE TITLE
can i choice the c# version to see the compiler code for old version of c#?

### ISSUE THREAD

**Issue by ahmeteid7** [icsharpcode/ilspy-vscode#420]
in desktop version i can display the compiler code in any version of c#, how i can do that in the extension version

**Comment by Rpinski** [comment]
Just click the "Output:" item in status bar when viewing decompiled code:

![image](https://github.com/icsharpcode/ilspy-vscode/assets/1767539/83523e98-e9c7-4e43-bbc1-739cb5d1053e)

or use the "ILSpy: Output language" command in VSCode command palette. Then you will be presented a list of C# versions to choose one for the output:

![image](https://github.com/icsharpcode/ilspy-vscode/assets/1767539/3ce45f4b-3f72-41a5-b43f-de62f607474d)

**Comment by ahmeteid7** [comment]
I'm using linux(zorin lite 16 xfce), i have dotnet 6,7,8, the output can't list the c# version,also i can't found that command:ILSpy: Output language
![image](https://github.com/icsharpcode/ilspy-vscode/assets/115186023/2c132eed-498b-4435-bbdf-3ae0671eb229)
![image](https://github.com/icsharpcode/ilspy-vscode/assets/115186023/d92b2f04-fa90-4fe9-a6e2-a7c91c361dd8)

**Comment by Rpinski** [comment]
These options are only available when your active editor is an ILSpy decompilation result (you seem to have open a normal code editor with C# code, instead). There is another alternative: You may set the output language in VSCode settings:

![ILSpy Output Language](https://github.com/icsharpcode/ilspy-vscode/assets/1767539/2a49d986-1504-4f90-ab29-edc2fff44131)

**Comment by ahmeteid7** [comment]
Thank u very much ,it's worked with me
