### ISSUE TITLE
': Unable to write file (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/ilspy-decompilation.cs')

### ISSUE THREAD

**Issue by MateusAmin** [icsharpcode/ilspy-vscode#46]
I get this error when trying to save the file. On a Debian machine.

Error Output:

Failed to save 'ilspy-decompilation.cs': Unable to write file (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/ilspy-decompilation.cs')

Steps Taken:

Updating workspace permissions using chmod -r 775 [Did not work]
Running vscode as sudo [Did work]

**Comment by MateusAmin** [comment]
What directory would it be using to write to?

**Comment by jeremymeng** [comment]
Could you use File > Save As ...?

The decompiled code are displayed in a temporary document.  Last time I checked there isn't a way to hint it's file path.  I do see it shows `\ilspy-decompilation.cs` in the hover over tooltip.

**Comment by jeremymeng** [comment]
Actually it is supported to specify a path, but I don't have a good path to put there

> `untitled`-scheme: A new file that should be saved on disk, e.g. `untitled:c:\frodo\new.js`. The language will be derived from the file name.

**Comment by jeremymeng** [comment]
The decompiled code are now saved to temp files and opened from there.  Closing this.
