### ISSUE TITLE
ilspy not working in vscode for mac 

### ISSUE THREAD

**Issue by MarsonShine** [icsharpcode/ilspy-vscode#48]
Environment:
macOS Catalina 10.15.3
vscode 1.41.1
ILSpy 0.7.10

when i installed extension and press `Ctrl+Shift+P`
select "decomplier il assembly" 
<img width="850" alt="截屏2020-02-20下午4 25 12" src="https://user-images.githubusercontent.com/17610342/74914629-bd8a2500-53fd-11ea-9dd3-a9349157f62b.png">
then nothing!
<img width="761" alt="截屏2020-02-20下午4 27 17" src="https://user-images.githubusercontent.com/17610342/74914897-34bfb900-53fe-11ea-893f-c68c8674da67.png">

and reopen、reinstall not working

please give me some advice
thanks

**Comment by christophwille** [comment]
I am on 1.42.1, but everything else is identical. 

When I choose an assembly in the dialog + click "Select assembly" it opens the assembly in the tree (takes about a second or so initially).

**Comment by MarsonShine** [comment]
i tried agian,but same result, the tree is empty.
1.42.1 is ilspy?
but 1.41.1 is newest in market.where download？compile source code？

**Comment by christophwille** [comment]
1.42.1 is the VSCode version.

**Comment by jeremymeng** [comment]
@MarsonShine could you please share the output of the ilspy-vscode log after selecting the assembly?

![image](https://user-images.githubusercontent.com/7583839/75087348-da088900-54f3-11ea-9c19-44a9f8d77fa2.png)

**Comment by MarsonShine** [comment]
now, my vscode version is 1.42.1 but no change
detail info for vscode bellow
```
版本: 1.42.1
提交: c47d83b293181d9be64f27ff093689e8e7aed054
日期: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

```
and there are some pictures
<img width="1434" alt="截屏2020-02-22下午3 00 32" src="https://user-images.githubusercontent.com/17610342/75088151-74181200-5584-11ea-88af-e04c66731ac4.png">

**Comment by jeremymeng** [comment]
@MarsonShine I assume you have `mono` installed? What's your output of `mono --version`?

**Comment by MarsonShine** [comment]
yes, i'm installed mono
 
<img width="851" alt="截屏2020-02-22下午5 20 54" src="https://user-images.githubusercontent.com/17610342/75089835-c3b40900-5597-11ea-84bd-695c2c85273c.png">

**Comment by MarsonShine** [comment]
oh!! lucky
in  just, i'm try again reinstall ilspy. it show tree view successfully.but I don't know why
i'm sorry about it that token up your time.
now close issue

**Comment by jeremymeng** [comment]
Glad to hear that it is working for you now!

**Comment by sethidden** [comment]
If you get this, CTRL+SHIFT+P > Reload Window then add the assemly to ILSpy decompiled members window again. Should work.
