### ISSUE TITLE
RFC: Shipping for .NET Core

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ilspy-vscode#55]
https://github.com/dotnet/vscode-dotnet-runtime

That way we could easily target .NET Core *and* be sure that the correct runtime is on the machine. Beta at time of me creating this issue. But this is intended as discussion - do we want to go that way?

**Comment by jeremymeng** [comment]
It looks promising! Definitely better than shipping platform-specific self-contained executables.

**Comment by christophwille** [comment]
See sample https://github.com/dotnet/vscode-dotnet-runtime/tree/master/sample
See https://github.com/dotnet/vscode-dotnet-runtime/tree/master/vscode-dotnet-runtime-extension
See https://github.com/dotnet/vscode-dotnet-runtime/blob/master/Documentation/troubleshooting-runtime.md

**Comment by christophwille** [comment]
The new version will show a loading indicator after installation:

![image](https://user-images.githubusercontent.com/344208/121516344-6216e880-c9ee-11eb-9d01-b65af8e1aff8.png)

Clicking leads to details about download and installation:

![image](https://user-images.githubusercontent.com/344208/121516396-73f88b80-c9ee-11eb-9976-a2f279b7fc3e.png)

@Rpinski https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#install-script-timeouts if we can, we should up that from the default because today I was bitten by a slow network.

**Comment by christophwille** [comment]
Timeout documented in Wiki https://github.com/icsharpcode/ilspy-vscode/wiki/Troubleshooting
