### ISSUE TITLE
Possible to sort the decompiled browser?

### ISSUE THREAD

**Issue by gnarf** [icsharpcode/ilspy-vscode#56]
In a large namespace, it's really hard to find a particular class / type because the values seem to be ordered in compile order instead of alphabetically.

Would it be possible to sort the brower so I dont have to scan through miles of stuff like this to find the specific thing I'm looking for?

![image](https://user-images.githubusercontent.com/549355/80289008-cbb03680-8709-11ea-8c5f-3315fab1d182.png)

**Comment by jeremymeng** [comment]
@gnarf great feedback!  Yes it would be better to sort the nodes. Also nice if a search filter could be possible.

**Comment by justingdelisle** [comment]
> @gnarf great feedback! Yes it would be better to sort the nodes. Also nice if a search filter could be possible.

I completely agree! Searching and sorting would be great!
