### ISSUE TITLE
[Feature Request] Search and location dump

### ISSUE THREAD

**Issue by aress31** [icsharpcode/ilspy-vscode#57]
As far as I know, the `ILSpy extension` automatically dumps the decompiled and disassembled files into the `current user's temp folder`. Adding the option to dump these contents into an arbitrary location would be a good addition. But more importantly, I believe that adding the ability to use `VScode built-in search feature` to look for specific strings should be a must have.

**Comment by justingdelisle** [comment]
Upvote!

**Comment by Rpinski** [comment]
The extension doesn't dump decompiled code to files anymore and uses VSCode's editor buffers, instead. Searching is possible, too.

I think this issue can be closed now.
