### ISSUE TITLE
Difficult to pick assembly to decompile in current workspace: filenames are too long 

### ISSUE THREAD

**Issue by NikiforovAll** [icsharpcode/ilspy-vscode#61]
As you can see on the screenshot below, the only thing I can see is the base path of the file, which is troublesome. It should be possible to show a relative path or at least make a configuration option for it.

![image](https://user-images.githubusercontent.com/8037439/89257138-49031580-d62e-11ea-84d8-3e77121d3011.png)

I would be happy to contribute, please let me know if you accept contributions.

**Comment by jeremymeng** [comment]
Contributions are absolutely welcome!

**Comment by NikiforovAll** [comment]
@jeremymeng. Do you find the idea that I coined above useful? What the default value for this config would be?

**Comment by jeremymeng** [comment]
I think it might be a good idea to show last part of the full path. We can also check how vscode handles long paths when Ctrl + P, and follow its approach.

**Comment by NikiforovAll** [comment]
Yes, it will do the trick. 

[QuickPickItem](https://code.visualstudio.com/api/references/vscode-api#QuickPickItem) has additional fields to control how an item is displayed.

I will prepare PR for this.
