### ISSUE TITLE
Linux mono 6.8.0 error

### ISSUE THREAD

**Issue by EmptyBucket** [icsharpcode/ilspy-vscode#64]
VS Code version: 1.48.2

Operation System and version: manjaro linux 5.6

(MacOs or Linux) Mono version: 6.8.0 (Linux)

## Steps to reproduce
1) ctrl+shift+p
2) enter ilspy pick
3) select dll e.g. lightinject.dll(version 6.2.0)

## Expected  behavior
Tree in ILSPY DECOMPILED MEMBERS

## Actual behavior
Nothing

## ilspy-vscode extension logs
Starting ILSpy.Host server at 8/27/2020, 1:37:13 PM

ILSpy.Host server started wth Mono
    Path: /home/strix/.vscode/extensions/icsharpcode.ilspy-vscode-0.9.0/bin/ilspy-host/ILSpy.Host.exe
    PID: 1276

ILSpy.Host: --stdio --encoding utf-8
﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"ILSpy.Host.Startup","Message":"ILSpy.Host server running using Stdio."},"Seq":1,"Type":"event"}
2020-08-27 13:37:13 INF ILSpy.Host server running using Stdio.
2020-08-27 13:37:14 DBG Hosting starting
2020-08-27 13:37:14 DBG Hosting started
Enqueue Normal request for /addassembly.
Processing Normal queue
    makeRequest: /addassembly (1), data={"AssemblyPath":"/home/strix/RiderProjects/kpi/kpi.api/src/hosts/WebApi/bin/Debug/netcoreapp3.1/LightInject.dll"}
2020-08-27 13:37:14 INF "Request starting HTTP/1.1 POST http:///addassembly application/json "

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x5631c6f65337 - mono : (null)
	0x5631c6f656fc - mono : (null)
	0x5631c6f0fe90 - mono : (null)
	0x5631c6f648ba - mono : (null)
	0x7fa10f999960 - /usr/lib/libpthread.so.0 : (null)
	0x7fa10f7e0355 - /usr/lib/libc.so.6 : gsignal
	0x7fa10f7c9853 - /usr/lib/libc.so.6 : abort
	0x7fa10f823878 - /usr/lib/libc.so.6 : (null)
	0x7fa10f82ad3a - /usr/lib/libc.so.6 : (null)
	0x7fa10f82bf74 - /usr/lib/libc.so.6 : (null)
	0x40446dee - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x7fa106dfb700 from 0x7fa1078fd700
Pkilling 0x7fa10ca23700 from 0x7fa1078fd700
Pkilling 0x7fa107cff700 from 0x7fa1078fd700
Pkilling 0x7fa1067eb700 from 0x7fa1078fd700
Pkilling 0x7fa107afe700 from 0x7fa1078fd700
Pkilling 0x7fa1076fc700 from 0x7fa1078fd700
Pkilling 0x7fa106bf6700 from 0x7fa1078fd700
Pkilling 0x7fa1069f0700 from 0x7fa1078fd700
Pkilling 0x7fa10f79f780 from 0x7fa1078fd700
Entering thread summarizer pause from 0x7fa1078fd700
Finished thread summarizer pause from 0x7fa1078fd700.

Waiting for dumping threads to resume

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fa10f7e0355):0x7fa10f7e0345  d2 4c 89 ce bf 02 00 00 00 b8 0e 00 00 00 0f 05  .L..............
0x7fa10f7e0355  48 8b 84 24 08 01 00 00 64 48 2b 04 25 28 00 00  H..$....dH+.%(..
0x7fa10f7e0365  00 75 24 44 89 c0 48 81 c4 18 01 00 00 c3 0f 1f  .u$D..H.........
0x7fa10f7e0375  44 00 00 48 8b 15 f1 3a 18 00 f7 d8 41 b8 ff ff  D..H...:....A...

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Object:__icall_wrapper_mono_marshal_free <0x0006d>
	  at ICSharpCode.Decompiler.Metadata.DotNetCorePathFinder:realpath <0x0013f>
	  at ICSharpCode.Decompiler.Metadata.DotNetCorePathFinder:FindDotNetExeDirectory <0x0026b>
	  at ICSharpCode.Decompiler.Metadata.DotNetCorePathFinder:.ctor <0x00147>
	  at ICSharpCode.Decompiler.Metadata.DotNetCorePathFinder:.ctor <0x0008b>
	  at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver:FindAssemblyFile <0x00197>
	  at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver:Resolve <0x0003b>
	  at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem:.ctor <0x00a68>
	  at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem:.ctor <0x00043>
	  at ICSharpCode.Decompiler.CSharp.CSharpDecompiler:CreateTypeSystemFromFile <0x00153>
	  at ICSharpCode.Decompiler.CSharp.CSharpDecompiler:.ctor <0x0003b>
	  at ILSpy.Host.Providers.SimpleDecompilationProvider:AddAssembly <0x000bf>
	  at ILSpy.Host.AddAssemblyMiddleware:Handle <0x00084>
	  at <>c__DisplayClass5_0:<Invoke>b__0 <0x00034>
	  at System.Threading.Tasks.Task:InnerInvoke <0x00060>
	  at System.Threading.Tasks.Task:Execute <0x00037>
	  at System.Threading.Tasks.Task:ExecutionContextCallback <0x0005b>
	  at System.Threading.ExecutionContext:RunInternal <0x00191>
	  at System.Threading.ExecutionContext:Run <0x00042>
	  at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x000f6>
	  at System.Threading.Tasks.Task:ExecuteEntry <0x000dc>
	  at System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem <0x00026>
	  at System.Threading.ThreadPoolWorkQueue:Dispatch <0x00279>
	  at System.Threading._ThreadPoolWaitCallback:PerformWaitCallback <0x0001c>
	  at <Module>:runtime_invoke_bool <0x00086>
=================================================================

**Comment by jeremymeng** [comment]
@siegfriedpammer @christophwille Any ideas? I wonder whether this would also repro using mono and the console decompiler.

**Comment by siegfriedpammer** [comment]
@EmptyBucket do you have .NET Core installed on your machine? The exception happens in the part of the decompiler that tries to resolve assembly references. It crashes during initialization, while looking for the dotnet executable.

Would it be possible for you to post some details on the assembly that you are trying to open? Which target framework was it compiled for? Which version, etc. Thank you!

From the error message it looks like a .NET Core / .NET Standard assembly, if that is not the case, then the error is that the decompiler wrongly thinks it's dealing with a .NET Core / .NET Standard assembly. If it indeed is a .NET Core / .NET Standard assembly and you do not have .NET Core installed, this might be causing the crash and we will have to improve the error handling in that area and you might be able to solve the issue by installing the matching .NET Core version required by the assembly you try to decompile.

**Comment by danbugs** [comment]
I have the same issue. I was trying to decompile `System.IO.Filesystem.dll` and I have .NET Core installed. Any ideas how to fix this? Thanks in advance!

**Comment by almaceleste** [comment]
Do you have a `mono-complete` package installed?
I had the same behavior and after installing complete mono ILSpy successfully decompiled a .dll file.

**Comment by danbugs** [comment]
@almaceleste -- Thanks for the response. I tried:

```
sudo apt-get update
sudo apt-get install mono-complete
```

... but saw no change in the result.

**Comment by Id405** [comment]
I have the same issue on arch linux
```
mono --version
Mono JIT compiler version 6.12.0 (makepkg/a22ed3f094e Tue Dec 22 06:01:50 PM -03 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

```
Starting ILSpy.Host server at 3/29/2021, 3:23:47 PM

ILSpy.Host server started wth Mono
    Path: /home/lily/.vscode-oss/extensions/icsharpcode.ilspy-vscode-0.9.0/bin/ilspy-host/ILSpy.Host.exe
    PID: 1185699

ILSpy.Host: --stdio --encoding utf-8
﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"ILSpy.Host.Startup","Message":"ILSpy.Host server running using Stdio."},"Seq":1,"Type":"event"}
2021-03-29 15:23:47 INF ILSpy.Host server running using Stdio.
2021-03-29 15:23:47 DBG Hosting starting
2021-03-29 15:23:47 DBG Hosting started
Enqueue Normal request for /addassembly.
Processing Normal queue
    makeRequest: /addassembly (1), data={"AssemblyPath":"/home/lily/Dev/AOAlchemy/libs/Assembly-CSharp.dll"}
2021-03-29 15:23:47 INF "Request starting HTTP/1.1 POST http:///addassembly application/json "

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x561900e1affd - mono : 
	0x561900e1b3a9 - mono : 
	0x561900dc59e9 - mono : 
	0x561900e1a550 - mono : 
	0x7fabef967960 - /usr/lib/libpthread.so.0 : 
	0x7fabef7a7ef5 - /usr/lib/libc.so.6 : gsignal
	0x7fabef791862 - /usr/lib/libc.so.6 : abort
	0x7fabef7e9f38 - /usr/lib/libc.so.6 : 
	0x7fabef7f1bea - /usr/lib/libc.so.6 : 
	0x7fabef7f303c - /usr/lib/libc.so.6 : 
	0x7fabef7f6ca8 - /usr/lib/libc.so.6 : cfree
	0x41f0e6fe - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x140376433657664x from 0x140376283022912x
Pkilling 0x140376289363520x from 0x140376283022912x
Pkilling 0x140376302671424x from 0x140376283022912x
Pkilling 0x140376298468928x from 0x140376283022912x
Pkilling 0x140376305301056x from 0x140376283022912x
Pkilling 0x140376385992256x from 0x140376283022912x
Pkilling 0x140376287262272x from 0x140376283022912x
Pkilling 0x140376285140544x from 0x140376283022912x
Pkilling 0x140376300570176x from 0x140376283022912x
Entering thread summarizer pause from 0x140376283022912x
Finished thread summarizer pause from 0x140376283022912x.
Failed to create breadcrumb file (null)/crash_hash_0x3c93ed5a3

Waiting for dumping threads to resume

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fabef7a7ef5):0x7fabef7a7ee5  d2 4c 89 ce bf 02 00 00 00 b8 0e 00 00 00 0f 05  .L..............
0x7fabef7a7ef5  48 8b 84 24 08 01 00 00 64 48 2b 04 25 28 00 00  H..$....dH+.%(..
0x7fabef7a7f05  00 75 24 44 89 c0 48 81 c4 18 01 00 00 c3 0f 1f  .u$D..H.........
0x7fabef7a7f15  44 00 00 48 8b 15 31 3f 18 00 f7 d8 41 b8 ff ff  D..H..1?....A...

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Object:__icall_wrapper_mono_marshal_free <0x0006d>
	  at ICSharpCode.Decompiler.Metadata.DotNetCorePathFinder:realpath <0x00137>
	  at ICSharpCode.Decompiler.Metadata.DotNetCorePathFinder:FindDotNetExeDirectory <0x0026b>
	  at ICSharpCode.Decompiler.Metadata.DotNetCorePathFinder:.ctor <0x00147>
	  at ICSharpCode.Decompiler.Metadata.DotNetCorePathFinder:.ctor <0x0008b>
	  at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver:FindAssemblyFile <0x00197>
	  at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver:Resolve <0x0003b>
	  at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem:.ctor <0x00a68>
	  at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem:.ctor <0x00043>
	  at ICSharpCode.Decompiler.CSharp.CSharpDecompiler:CreateTypeSystemFromFile <0x00153>
	  at ICSharpCode.Decompiler.CSharp.CSharpDecompiler:.ctor <0x0003b>
	  at ILSpy.Host.Providers.SimpleDecompilationProvider:AddAssembly <0x000bf>
	  at ILSpy.Host.AddAssemblyMiddleware:Handle <0x00084>
	  at <>c__DisplayClass5_0:<Invoke>b__0 <0x00034>
	  at System.Threading.Tasks.Task:InnerInvoke <0x00060>
	  at System.Threading.Tasks.Task:Execute <0x00037>
	  at System.Threading.Tasks.Task:ExecutionContextCallback <0x0005b>
	  at System.Threading.ExecutionContext:RunInternal <0x00191>
	  at System.Threading.ExecutionContext:Run <0x00042>
	  at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x000f6>
	  at System.Threading.Tasks.Task:ExecuteEntry <0x000dc>
	  at System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem <0x00026>
	  at System.Threading.ThreadPoolWorkQueue:Dispatch <0x00279>
	  at System.Threading._ThreadPoolWaitCallback:PerformWaitCallback <0x0001c>
	  at <Module>:runtime_invoke_bool <0x00086>
=================================================================
```

**Comment by christophwille** [comment]
This issue is no longer applicable as #55 has been implemented.
