### ISSUE TITLE
Publish extension on open-vsx.org, so it can be used in VSCodium, Gitpod

### ISSUE THREAD

**Issue by geekley** [icsharpcode/ilspy-vscode#65]
Can you please publish the extension on Open-VSX, so it can reach more users?
[open-vsx.org](https://open-vsx.org) is an alternative to VS Marketplace, [that can legally be used](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace) in Visual Studio Code forks like [VSCodium](https://github.com/VSCodium/vscodium#why-does-this-exist), [GitPod](https://www.gitpod.io/features/#vs).
Of course, you don't have to change anything in the extension itself (except maybe some README URLs that point to VS Marketplace, if you care about these details).

[The process](https://github.com/eclipse/openvsx/blob/master/cli/README.md) is pretty much the same as publishing to VS Marketplace.
It can even be automated, see:
https://github.com/open-vsx/publish-extensions
> Though the preferred solution for such a situation is to convince the maintainers to start publishing themselves, you can add the extensions here to have them published by our CI workflow.

You can [claim ownership](https://github.com/eclipse/openvsx/wiki/Namespace-Access) of your namespace `icsharpcode`, and officially support the extension there.

More details on [this blog post](https://www.gitpod.io/blog/open-vsx/).

**Comment by christophwille** [comment]
As a stopgap - would publishing a release with the binary vsix on GH be ok?

**Comment by geekley** [comment]
Well, it's already possible to download the VSIX file from VS Marketplace website and install it manually.
The problem is that's only for a specific version. You don't get automatic updates unless it's from the store.

So if the goal is to allow people to get release notifications of new versions (by watching the repo), I guess that helps a little, but I think it's not needed.

**Comment by geekley** [comment]
Oh. I just noticed VS Marketplace site only allows download of latest version, so publishing releases here is actually a good idea, even if just for archival purposes.

**Comment by christophwille** [comment]
https://marketplace.visualstudio.com/items?itemName=icsharpcode.ilspy-vscode&ssr=false#version-history

A couple of releases can be downloaded.

**Comment by geekley** [comment]
I don't know if this is a trivial change to make or if it would only complicate things, but ...
Is it possible to make it fallback to use existing Mono in Linux, when `ms-dotnettools.vscode-dotnet-runtime` is not available? Is not in Open-VSX (yet?) and I'd rather not install .NET Core / 5 anyways ...

If having the option to use Mono isn't possible or desired, I suppose I'll just stay in v0.10.0.

**Comment by christophwille** [comment]
No, special-casing just for open-vsx is not really an option (I will be blunt: the market is too small)

**Comment by christophwille** [comment]
I am closing this as we have no intention to publish there (at least for the foreseeable future).

**Comment by geekley** [comment]
> the market is too small

Would you consider maybe re-evaluating this? An [official post](https://www.globenewswire.com/news-release/2023/06/27/2695137/0/en/The-Open-VSX-Registry-a-Vendor-Neutral-Community-Supported-Alternative-to-the-Visual-Studio-Marketplace-Gets-its-Own-Working-Group-at-the-Eclipse-Foundation.html) (from 5 months ago) says at that point it:
> hosts nearly 3,000 extensions from over 1,500 different publishers, with new publishers and extensions being added daily. Since the Open VSX Registry became available in 2021, developers have consumed more than 40M extensions, with downloads now exceeding 2M per month

Plus, they now have a working group which makes Open-VSX financially viable in the long run (with sponsors like Google and other big companies). Again, no changes should be needed in the extension (I no longer care about Mono) and it should be easy to set up auto-publishing.

**Comment by Necklaces** [comment]
I'd like to add my vote to this, I'd love to see this extension on Open VSX.
