### ISSUE TITLE
[Feature request] Support on Linux w.o. Mono as dependency

### ISSUE THREAD

**Issue by fkromer** [icsharpcode/ilspy-vscode#66]
Would be great if one could use the extension on Linux without depending on Mono. For .NET Core this should be possible I guess.

**Comment by Rpinski** [comment]
As soon as the modernization described in #67 is finished (where we also plan migration to .NET 5.0), the Mono dependency should disappear.

**Comment by fkromer** [comment]
@Rpinski Nice.

**Comment by christophwille** [comment]
As this is in progress (implemented, xplat validation needed), we'll track it via #55
