### ISSUE TITLE
Looking for Maintainer

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ilspy-vscode#67]
This repository is looking for a new maintainer. 

Note that the basis of the codebase is "old" in terms of the speed of change in the VSCode / JavaScript universe, so maybe `yo code` and porting in the existing code is a good starting point to see if you'd like to get on board. Both JS and .NET knowledge is required, some OmniSharp / LSP definitely helps (also take a look at #55 to see how we'd like to shape the runtime dependency story going forward)

**Comment by Rpinski** [comment]
I've started work on modernization of the extension's codebase. Main goals:

- Getting rid of parts based on old OmniSharp code
- Building the protocol between extension and server on top of LSP
- As a first step just porting existing logic on both sides to the LSP interface

The progress can be seen on my fork right now:

https://github.com/Rpinski/ilspy-vscode/tree/lsp-based
