### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nicolaskruger** [icsharpcode/ilspy-vscode#75]
- Issue Type: `Performance`
- Extension Name: `ilspy-vscode`
- Extension Version: `0.11.0`
- OS Version: `Linux x64 5.8.0-55-generic`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/icsharpcode.ilspy-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Rpinski** [comment]
When does it happen? Directly when starting VS Code? Or when using the extension later?

**Comment by Rpinski** [comment]
Might be related to #76 and #77, since the startup issues on Linux introduced with 0.11 release might cause several strange effects, even in other extensions. But I can't tell without additional info, only can suggest to test with next extension update.

**Comment by christophwille** [comment]
@nicolaskruger did you get a chance to test the latest version?

**Comment by nicolaskruger** [comment]
this issue just happen one one time, i remove some extensions and done.
