### ISSUE TITLE
IntelliSense shows "Loading..." when the icsharpcode.ilspy-vscode extension is enabled

### ISSUE THREAD

**Issue by almaceleste** [icsharpcode/ilspy-vscode#77]
VS Code version: 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)

Operation System and version: Ubuntu 21.04 (Linux x64 5.11.0-16-lowlatency)

(MacOs or Linux) Mono version: 6.12.0.122

## Steps to reproduce
1. Enable the `icsharpcode.ilspy-vscode` extension
2. Create new empty file
3. Push `Ctrl`+`S` to save file
4. Enter name and click `Save`
5. Get a lingering toast `Running 'File Create' participants`
6. Push `Ctrl`+`Space` to get IntelliSense suggestions
7. Get a `Loading...` message
![image](https://user-images.githubusercontent.com/36765595/123555884-1192df80-d791-11eb-8864-29bc75bdbaf8.png)

## Expected  behavior
1. Do not get the lingering toast `Running 'File Create' participants`
2. Do not get the `Loading...` message, but get the IntelliSense suggestions

## Actual behavior
1. the toast `Running 'File Create' participants`
2. the `Loading...` message, but not the IntelliSense suggestions

## ilspy-vscode extension logs
have no the ilspy-vscode output

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.56GB (1.01GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 0bfd8309-f876-4390-99c3-dddd9b122049|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
binariesv615:30325510
vsccppwtct:30329789

```

</details>

**Comment by Rpinski** [comment]
@almaceleste Would you mind trying the latest build of the extension:

https://github.com/icsharpcode/ilspy-vscode/suites/3106843610/artifacts/71064394

It doesn't fix anything, but it logs all steps of the startup process. This would help me a lot to analyze if one of the steps hangs or maybe blocks the extension host etc., which might influence other extensions.

The artifact ZIP contains a .vsix package, which can be installed into VS Code with _Extensions_ -> ... -> _Install from VSIX..._
After installation you will see a new output category "ILSpy Extension"

![ILSpy Extension output](https://user-images.githubusercontent.com/1767539/123524228-112f1180-d6c9-11eb-85bb-caa8baf11f99.png)

Could you post the output seen there after VS Code has finished starting? And additionally, could you tell if there is anything suspicious shown in "Log (Extension Host)" output?

Many thanks in advance!

**Comment by Rpinski** [comment]
Finally found the issue related to check of .NET runtime's dependencies on Linux, which caused the startup process to hang. Sorry for the inconvenience, will be fixed ASAP with next extension update.
