### ISSUE TITLE
Where is the decompiled code written to?

### ISSUE THREAD

**Issue by thundersen** [icsharpcode/ilspy-vscode#79]
Where are the temporary files containing the decompiled code located? I would like to search them.

VS Code version:
`1.60.2`

Operation System and version:
```
$ uname -srvmpio
Linux 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021
x86_64 x86_64 x86_64 GNU/Linux
```

(MacOs or Linux) Mono version:
`Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-2 Wed Feb 26 23:23:50 UTC 2020)`

**Comment by Rpinski** [comment]
Hi @thundersen,
Since release of 0.12 there are no temporary files anymore. We are using [Virtual Documents](https://code.visualstudio.com/api/extension-guides/virtual-documents), which are present in memory only.

**Comment by thundersen** [comment]
Thanks @Rpinski. Fair enough. Do you know of any other way to search through the decompiled code?

**Comment by Rpinski** [comment]
@thundersen Since decompiled code is opened in VS Code's usual editor, you can use its text search as with any other editor (Ctrl+F)

Or do you mean searching for types and symbols through whole assembly (as in standalone ILSpy application)? The extension doesn't support that at the moment.
